CREATE TABLE inventario_motocicleta (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vehiculo_id INTEGER NOT NULL,
    conductor_id INTEGER NOT NULL,
    fecha_inventario TEXT NOT NULL,
    fecha_entrega TEXT,
    odometro INTEGER,
    observaciones TEXT,
    retrovisores TEXT,
    llantas TEXT,
    llanta_delantera TEXT,
    llanta_trasera TEXT,
    direccionales TEXT,
    foco_delantero TEXT,
    cadena TEXT,
    topes_manubrio TEXT,
    tope_manubrio_derecho TEXT,
    tope_manubrio_izquierdo TEXT,
    stop TEXT,
    luz_trasera TEXT,
    luces_muertas TEXT,
    orquilla_delantera TEXT,
    orquilla_trasera TEXT,
    resorte_stand TEXT,
    resorte_caballete TEXT,
    bujes_rin_trasero TEXT,
    bujias TEXT,
    cable_clutch TEXT,
    cable_acelerador TEXT,
    cable_velocimetro TEXT,
    tapon_aceite TEXT,
    micas_direccionales TEXT,
    micas_direccionales_delanteras TEXT,
    micas_direccionales_traseras TEXT,
    claxon TEXT,
    retenes TEXT,
    nivel_aceite TEXT,
    ajustadores_cadenas TEXT,
    guardafangos TEXT,
    tapaderas_lados TEXT,
    tapadera_filtro TEXT,
    tapadera_pila TEXT,
    balatas_delanteras TEXT,
    balatas_traseras TEXT,
    pila TEXT,
    selector_cambios TEXT,
    relay_direccionales TEXT,
    guardacadenas TEXT,
    tope_asiento TEXT,
    hule_reposapie_izquierdo TEXT,
    hule_reposapie_derecho TEXT,
    reposamano TEXT,
    freno_delantero TEXT,
    clutch TEXT,
    liquido_freno TEXT,
    tolba_mofle TEXT,
    reposa_pies_copiloto_izquierdo TEXT,
    reposa_pies_copiloto_derecho TEXT,
    herramienta TEXT,
    switch_encendido TEXT,
    switch_luces TEXT,
    switch_direccionales TEXT,
    estetica_tanque_gasolina TEXT,
    condicion_marcadores TEXT,
    bujes_orquilla_trasera TEXT,
    foto_frontal TEXT,
    foto_trasera TEXT,
    foto_lateral TEXT,
    estatus TEXT DEFAULT 'ENTREGADA',
    fecha_actualizacion TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (vehiculo_id) REFERENCES vehiculos(id),
    FOREIGN KEY (conductor_id) REFERENCES conductores(id)
);